// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdhngnsrechcgodxmcgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkaG5nbnNyZWNoY2dvZHhtY2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNDMyNDYsImV4cCI6MjA0OTgxOTI0Nn0.TxfqLPiA5F_T1wRVAx5tY9Pc5wsNYU8ipatatzzP1j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);